#family:
#  family-name: "happy family"
#  father:
#    name: tom
#    age: ${random.int(30)}
#  mother:
#    alias:
#      - rose
#      - alice
#  child:
#    name: jack
#    age: 6
##    birth: "2025-12-12"
#    friends:
#      - hobby: football
#        gender: male
#      - hobby: sing
#        gender: female

spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
#  port: 8888

#指定需要使用的配置文件
#  profiles:
#    active: test
